### ISSUE TITLE
Config field

### ISSUE THREAD

**Issue by srenon33** [brenard/phplist-casldap-plugin#1]
When plugin is enabled the config fields was not displayed in the configuration page.
Did i missed something?

**Comment by kernhsab** [comment]
Same here, i've downloaded the last version of phplist3 (v3.2.4), but when i install the plugin i've no plugin config displayed in the configuration page.

**Comment by brenard** [comment]
Hi, You are right, something change in last release and plugin config fileds not displayed in the configuration page. I fix it in my last commit e67056ae690a31000e5d7676000bcc745e081c14.

More ever, I just [add info](https://github.com/brenard/phplist-casldap-plugin/blob/master/README.md#add-patch-to-trigger-automatic-cas-login) on a required small patch that you currently have to apply to permit to trigger CAS automatic login.

**Comment by kernhsab** [comment]
Hi i've downloaded your last commit and now i see the configuration. Thanks! 
But, i've also applied the patches to the files "defaultplugin.php" and "login.php" in lists/admin directory and i'm still not redirected to my cas login page. Howerver when i call "lists/admin/?page=logout" i'm redirected to my cas logout page. I've tried to debug but i'm stuck here...

**Comment by brenard** [comment]
On my fresh Debian Jessie installation, I have a bug like it : white page with only the PhpList header, can't login...

After some check, I found an recent issue in Net_LDAP2 library ([come with last security update](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812788)).
The workaround explain [here](https://github.com/pear/Net_LDAP2/commit/df99b63de9b2459b5e0cd94bd26f38f3010f992e) solve this problem on my installation. On Debian, this patch have to be applied on files installed in _/usr/share/php/Net/LDAP2/_ directory.

This bug throw a PHP Fatal error witch I can't catch so this problem could not be unfortunately more explicit... May be PhpList log mechanisms could handle this problem, but I'm not sure..

**Comment by kernhsab** [comment]
Thanks a lot for your help. Its work fine now :+1:

**Comment by brenard** [comment]
Nice ! I close this issue.

**Comment by brenard** [comment]
Nice ! I close this issue.
